autogluon/tabrepo

data/configs/configs_ftt.json, scripts/__init__.py, scripts/baseline_comparison/baselines.py, scripts/baseline_comparison/compare_results.py, scripts/baseline_comparison/evaluate_baselines.py, scripts/baseline_comparison/evaluate_utils.py, scripts/baseline_comparison/plot_utils.py, scripts/dataset_analysis.py, scripts/generate_latex_table_system_comparison.py, scripts/run_generate_all_configs.py, scripts/run_generate_amlb_config.py, scripts/show_repository_stats.py, tabrepo/contexts/_context_fetcher.py, tabrepo/contexts/context_2023_11_14.py, tabrepo/contexts/subcontext.py, tabrepo/contexts/utils.py, tabrepo/models/ftt/generate.py, tabrepo/predictions/tabular_predictions.py, tabrepo/repository/evaluation_repository.py, tabrepo/repository/time_utils.py, tabrepo/simulation/convert_memmap.py, tabrepo/simulation/sim_runner.py, tabrepo/simulation/simulation_context.py
- Numerous refactoring to fix some bugs in #54
- Added new results for model families FTT, TabPFN, Linear, and KNeighbors
- Code cleanup
=> [WIP] Refactor for 2024

scripts/dataset_analysis.py
Add a deep dive into runtime properties of TabRepo's models.
=> Add runtime analysis deep dive

scripts/baseline_comparison/evaluate_baselines.py, scripts/baseline_comparison/plot_utils.py
=> Fix pandas warnings

scripts/__init__.py, scripts/baseline_comparison/evaluate_baselines.py, tabrepo/contexts/_subcontext_utils.py, tabrepo/contexts/subcontext.py, tabrepo/repository/evaluation_repository.py, tabrepo/simulation/sim_output.py, tst/test_repository.py
- Add repo.subset inplace arg
- Add repo.force_to_dense inplace arg
- This helps to reduce the amount of inplace operations going on for new users. New users probably don't want to do inplace operations by default.
=> Add repo subset inplace arg

scripts/simulate/run_inspect_overfit.py, setup.py, tabrepo/__init__.py, tabrepo/contexts/utils.py, tabrepo/repository/__init__.py, tabrepo/repository/abstract_repository.py, tabrepo/repository/ensemble_mixin.py, tabrepo/repository/evaluation_repository.py, tabrepo/repository/evaluation_repository_collection.py, tabrepo/repository/ground_truth_mixin.py, tabrepo/simulation/configuration_list_scorer.py, tabrepo/simulation/ensemble_selection_config_scorer.py, tabrepo/simulation/simulation_context.py, tabrepo/simulation/single_best_config_scorer.py, tst/test_repository.py, tst/test_repository_collection.py
Resolves #65 
- Add EvaluationRepositoryCollection
=> Add EvaluationRepositoryCollection

examples/run_quickstart.py, tabrepo/contexts/context_artificial.py, tabrepo/repository/abstract_repository.py, tabrepo/repository/ensemble_mixin.py, tabrepo/simulation/simulation_context.py, tst/test_repository.py
Add ability to easily get the AutoGluon model hyperparameters to fit a given config or list of configs with AutoGluon.
=> Add AutoGluon hyperparameters fetching

tabrepo/__init__.py, tabrepo/evaluation/evaluator.py, tabrepo/repository/abstract_repository.py
Follow-up to #86 
- Create WIP Evaluator class, move `compare_metrics` and `plot_overall_rank_comparison` into `Evaluator`.
=> Move `compare_metrics` and `plot_overall_rank_comparison` to `Evaluator`

tabrepo/models/realmlp/generate.py
*Issue #, if available:* None
*Description of changes:* Added hyperparameter config generation for RealMLP.
=> Added RealMLP hyperparameter generation

examples/run_quickstart_new_config.py, tabrepo/benchmark/experiment/__init__.py, tabrepo/benchmark/experiment/experiment_constructor.py, tabrepo/benchmark/experiment/experiment_runner.py, tabrepo/benchmark/experiment/experiment_utils.py, tabrepo/benchmark/models/ag/__init__.py, tabrepo/benchmark/models/ag/ebm/ebm_model.py, tabrepo/benchmark/models/ag/realmlp/realmlp_model.py, tabrepo/benchmark/models/ag/tabdpt/TabDPT_class.py, tabrepo/benchmark/models/ag/tabdpt/internal/tabdpt.py, tabrepo/benchmark/models/ag/tabdpt/internal/tabdpt_model.py, tabrepo/benchmark/models/ag/tabdpt/internal/tabdpt_utils.py, tabrepo/benchmark/models/ag/tabdpt/tabdpt_model.py, tabrepo/benchmark/models/ag/tabpfnv2/tabpfnv2_client_model.py, tabrepo/benchmark/models/ag/tabpfnv2/tabpfnv2_model.py, tabrepo/benchmark/models/model_register.py, tabrepo/benchmark/models/simple/__init__.py, tabrepo/benchmark/models/simple/simple_lightgbm.py, tabrepo/benchmark/models/wrapper/AutoGluon_class.py, tabrepo/benchmark/models/wrapper/__init__.py, tabrepo/benchmark/models/wrapper/abstract_class.py, tabrepo/benchmark/models/wrapper/ag_model.py
Add TabRepo 2.0 model running logic + model code
=> Add TabRepo2 Models

tabrepo/benchmark/experiment/experiment_constructor.py, tabrepo/benchmark/experiment/experiment_runner.py, tabrepo/benchmark/experiment/experiment_utils.py
- Add AGModelOuterExperiment, code cleanup
=> Add AGModelOuterExperiment, code cleanup

tabrepo/benchmark/models/ag/__init__.py, tabrepo/benchmark/models/ag/tabicl/tabicl_model.py, tabrepo/benchmark/models/model_register.py
=> Add TabICL

tabrepo/models/tabicl/generate.py
*Issue #, if available:* None
*Description of changes:* Added a search space for TabICL.
=> Add TabICL search space

tabflow/configs/method_configs.yaml, tabflow/docker/.dockerignore, tabflow/docker/Dockerfile_SM, tabflow/docker/build_docker.sh, tabflow/pyproject.toml, tabflow/tabflow/cli/download.py, tabflow/tabflow/cli/evaluate.py, tabflow/tabflow/cli/launch_jobs.py, tabflow/tabflow/core/resource_manager.py, tabflow/tabflow/utils/constants.py, tabflow/tabflow/utils/logging_utils.py, tabflow/tabflow/utils/s3_utils.py, tabflow/tabflow/utils/utils.py, tabrepo/benchmark/experiment/experiment_utils.py, tabrepo/utils/cache.py
Note: for the main PR, refer to here: https://github.com/autogluon/tabrepo/pull/109
WIP PR. Not ready for review. This is the same changes as in #77 after rebasing to mainline.
Colab notebook demo of the new functionality: https://colab.research.google.com/drive/19D7gpRCI0gh1a0brMyE8IGp2K16Fzype?usp=sharing
=> [WIP] Model Fitting Logic

README.md, tabrepo/loaders/__init__.py
*Description of changes:* 
In slurm environment, it is typically not possible to write large files to home. This change allows to override the location easily.
=> Allow to change cache location

tabrepo/models/ebm/generate.py
=> add EBM model

tst/benchmark/models/test_ebm.py, tst/benchmark/models/test_realmlp.py, tst/benchmark/models/test_tabdpt.py, tst/benchmark/models/test_tabicl.py, tst/benchmark/models/test_tabpfnv2.py
- Add unit tests for new models
=> Add unit tests for new models

README.md, setup.py, tst/benchmark/models/test_ebm.py, tst/benchmark/models/test_realmlp.py, tst/benchmark/models/test_tabdpt.py, tst/benchmark/models/test_tabicl.py, tst/benchmark/models/test_tabpfnv2.py
=> Add optional dependencies

tabrepo/benchmark/models/ag/modernnca/modernnca_model.py, tabrepo/models/modernnca/generate.py
Issue #, if available: None
Description of changes: Added RTDL quantile transform, missing indicator, automatic batch size function.
=> Update ModernNCA settings

examples/tabarena/run_tabarena_eval.py, tabrepo/paper/paper_runner.py, tabrepo/paper/paper_runner_tabarena.py, tabrepo/paper/paper_utils.py, tabrepo/tabarena/tabarena.py
*Issue #, if available:* None
*Description of changes:* Updated the main plot. Might have partially destroyed the horizontal barplot (use_y=True).
=> updated main figure

examples/tabarena/run_tabarena_eval_v2.py, tabrepo/paper/paper_runner.py, tabrepo/paper/paper_runner_tabarena.py
*Description of changes:* Made some plots prettier.
=> Updated plots

examples/tabarena/run_tabarena_eval_v2.py, tabrepo/paper/paper_runner.py, tabrepo/paper/paper_runner_tabarena.py, tabrepo/tabarena/tabarena.py
*Description of changes:* Updates to CDD plots, fixed normalized scores, etc.
=> some more plot updates

setup.py, tabrepo/benchmark/models/ag/realmlp/realmlp_model.py, tabrepo/benchmark/models/ag/tabdpt/tabdpt_model.py, tabrepo/utils/config_utils.py
=> fix: install AG and remove RealMLP error

tabrepo/benchmark/experiment/__init__.py, tabrepo/benchmark/experiment/experiment_runner_api.py, tabrepo/benchmark/task/__init__.py, tabrepo/benchmark/task/user_task.py, tabrepo/paper/paper_runner_tabarena.py, tst/benchmark/experiment/test_experiment_utils.py, tst/benchmark/task/test_user_task.py
Adding support for UserTasks that allow us to run with custom datasets (by wrapping them inside an offline OpenML task/dataset).
Also, improve the API of the runner function to enable better usability. If this is merged, I have to update the code in the example repo. (TODO: think about merging the repos)
---
=> [TabArena] Support for Custom Datasets & Refactor of Runner API

tabrepo/nips2025_utils/per_dataset_tables.py
Added a function to obtain per-dataset results as latex tables.
=> Add per-dataset tables function

tabrepo/nips2025_utils/end_to_end.py
Improve usage of end-to-end evaluation. 
=> Add logic for subsets and imputation for end-to-end eval

tabrepo/benchmark/experiment/experiment_constructor.py
N/A
Copy method_kwargs at initialization of experiment constructors.
=> Fix minor bug for running experiments with fit_args

tabrepo/benchmark/experiment/experiment_runner_api.py, tabrepo/benchmark/models/ag/ebm/ebm_model.py, tabrepo/benchmark/models/ag/tabdpt/tabdpt_model.py, tabrepo/benchmark/models/ag/tabicl/tabicl_model.py, tabrepo/benchmark/models/ag/tabpfnv2/tabpfnv2_model.py, tabrepo/benchmark/task/user_task.py, tabrepo/models/utils.py, tst/benchmark/task/test_user_task.py
=> Minimal Resoruces for TFMs 

tabrepo/utils/config_utils.py
=> add: support for modify init kwargs in experiments and docstring

tabrepo/models/tabpfnv2/generate.py
=> fix: tabpfnv2 config gen
